# Generated by Django 4.2.11 on 2024-04-23 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_watchlist_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='item',
            field=models.ForeignKey(db_column='listing_by', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watch_listing', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
