# Generated by Django 4.2.11 on 2024-04-23 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_closedlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedlisting',
            name='winner',
            field=models.ForeignKey(db_column='by_user', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
